-- Clients Table
CREATE TABLE CLIENTS (
    ID SERIAL PRIMARY KEY,
    CLIENT_NAME VARCHAR(100) NOT NULL,
    MAX_BANDWIDTH DECIMAL(10, 2) NOT NULL,
    CIR DECIMAL(10, 2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Bandwidth Stats Table
CREATE TABLE BANDWIDTH_STATS (
    ID SERIAL PRIMARY KEY,
    CLIENT_ID INT REFERENCES CLIENTS(ID),
    REQUESTED_BANDWIDTH DECIMAL(10, 2),
    ALLOCATED_BANDWIDTH DECIMAL(10, 2),
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Admins Table
CREATE TABLE ADMINS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO CLIENTS (
    CLIENT_NAME,
    MAX_BANDWIDTH,
    CIR
) VALUES (
    'Client A',
    100.00,
    50.00
),
(
    'Client B',
    200.00,
    100.00
),
(
    'Client C',
    150.00,
    75.00
);

INSERT INTO ADMINS (
    USERNAME,
    PASSWORD_HASH
) VALUES (
    'admin1',
    'hashed_password_1'
),
(
    'admin2',
    'hashed_password_2'
);